export const printerProducts = [
  {
    id: 1,
    name: '(Refurbished) Canon ImageClass MF3010 Color Multi-Function Laserjet Printer',
    price: '$208.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying',
      'Ideal For: Home and Office Use',
      'Type: Monochrome Laser Printer with CIS Scanner',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 8,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 5,
    imageUrl:
      'https://5.imimg.com/data5/JO/OB/CQ/GLADMIN-12/3010-2-500x500.jpg',
  },
  {
    id: 2,
    name: '(Refurbished) HP LaserJet Pro MFP M127fn Monochrome Printer',
    price: '$189.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Small Office Use',
      'Type: Monochrome Laser Printer with ADF',
      'Print Capability: Black & White Printing',
      'Maximum Monthly Duty Cycle: Up to 9,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 8,
    imageUrl:
      'https://5.imimg.com/data5/SELLER/Default/2021/11/KS/UG/JU/51056009/hp-multi-function-monochrome-laser-printer-126a-500x500.jpg',
  },
  {
    id: 3,
    name: '(Refurbished) Brother DCP-L2540DW Wireless Monochrome Printer',
    price: '$199.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying',
      'Ideal For: Home and Small Office Use',
      'Type: Monochrome Laser Printer with Duplex',
      'Print Capability: Black & White Printing',
      'Maximum Monthly Duty Cycle: Up to 10,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 2,
    imageUrl:
      'https://5.imimg.com/data5/SELLER/Default/2022/6/JX/FY/AS/81066857/brother-dcpl2540dw-wireless-compact-laser-printer.jpg',
  },
  {
    id: 4,
    name: '(Refurbished) Epson EcoTank L3150 Wi-Fi All-in-One Ink Tank Printer',
    price: '$249.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying',
      'Ideal For: Home and Office Use',
      'Type: Ink Tank Printer with Wi-Fi',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 5,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 7,
    imageUrl:
      'https://mediaserver.goepson.com/ImConvServlet/imconv/d07bea89ee1150c0193a52c14b65b7a293d04362/1200Wx1200H?use=banner&hybrisId=B2C&assetDescr=L3150_04_2-1',
  },
  {
    id: 5,
    name: '(Refurbished) Samsung Xpress M2070FW Wireless Monochrome Laser Printer',
    price: '$179.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Home and Small Office Use',
      'Type: Monochrome Laser Printer with ADF',
      'Print Capability: Black & White Printing',
      'Maximum Monthly Duty Cycle: Up to 10,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 9,
    imageUrl:
      'https://5.imimg.com/data5/SC/BK/MY-13283831/samsung-xpress-m2070w-wireless-monochrome-laser-printer-500x500.jpg',
  },
  {
    id: 6,
    name: '(Refurbished) Lexmark MB2236adw Monochrome Multifunction Laser Printer',
    price: '$269.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Small Office Use',
      'Type: Monochrome Laser Printer with Duplex',
      'Print Capability: Black & White Printing',
      'Maximum Monthly Duty Cycle: Up to 12,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 4,
    imageUrl: 'https://m.media-amazon.com/images/I/51rHPOFx-QL._SL1500_.jpg',
  },
  {
    id: 7,
    name: '(Refurbished) Xerox WorkCentre 6515/DNI Color Multifunction Printer',
    price: '$349.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Office Use',
      'Type: Color Laser Printer with Duplex',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 50,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 6,
    imageUrl:
      'https://5.imimg.com/data5/WZ/JY/AH/SELLER-87600638/xerox-workcentre-6515-dn-all-in-one-color-laser-printer.jpg',
  },
  {
    id: 8,
    name: '(Refurbished) Dell E525w Color Laser All-in-One Wireless Printer',
    price: '$229.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Home and Office Use',
      'Type: Color Laser Printer with Wi-Fi',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 30,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 3,
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhUhe5zBVF4b2yBZnRPSIz7u1gi_nmBTFDMw&s',
  },
  {
    id: 9,
    name: '(Refurbished) Kyocera ECOSYS M5526cdw Color Multifunction Printer',
    price: '$399.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Office Use',
      'Type: Color Laser Printer with Duplex',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 50,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 5,
    imageUrl:
      'https://5.imimg.com/data5/BR/AV/MY-26267484/kyocera-ecosys-m5526cdn-color-mfps-500x500.jpg',
  },
  {
    id: 10,
    name: '(Refurbished) Panasonic KX-MB1530 Monochrome Multifunction Printer',
    price: '$149.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying',
      'Ideal For: Home Use',
      'Type: Monochrome Laser Printer',
      'Print Capability: Black & White Printing',
      'Maximum Monthly Duty Cycle: Up to 8,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 2,
    imageUrl:
      'https://lh6.googleusercontent.com/proxy/FivfIzxjS6W0NEHVocnuh4kAq2b3SF7EjsgJWzhntvZel7hF7H4A51inSGGTPyE0YfKmyrHwhhKuPeGsVA',
  },
  {
    id: 11,
    name: '(Refurbished) Ricoh SP C250SF Color Multifunction Printer',
    price: '$319.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Office Use',
      'Type: Color Laser Printer',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 30,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 10,
    imageUrl: 'https://m.media-amazon.com/images/I/71QD-wvlLuL.jpg',
  },
  {
    id: 12,
    name: '(Refurbished) Sharp MX-C304W Compact Color Multifunction Printer',
    price: '$499.00',
    keyFeatures: [
      'Functions: Printing, Scanning, Copying, Faxing',
      'Ideal For: Office Use',
      'Type: Color Laser Printer with Duplex',
      'Print Capability: Color Printing',
      'Maximum Monthly Duty Cycle: Up to 60,000 Pages',
      'Warranty Period: 6 Months',
    ],
    quantity: 1,
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD0sjL8wW67-r2KqD2g_A0VToIy7MoQEZQhw&s',
  },
];
